server:
  port: 8888

jwt:
  header: JWTHeaderName
  secret: PjboyaabbccddPjboyaabbccddPjboyaabbccddPjboyaabbccddPjboyaabbccdd
  expiration: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/say_something?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
